### ISSUE TITLE
Public talks are not listed on the user's profile.

### ISSUE THREAD

**Issue by sbouaked** [loicknuchel/gospeak#58]
Exemple with **NodeJS news** talk in demo environment.

![image](https://user-images.githubusercontent.com/3003831/63699758-c53b8900-c821-11e9-92a6-68e2089db9e7.png)

![image](https://user-images.githubusercontent.com/3003831/63699976-2b281080-c822-11e9-8a7d-6e8903eb2f3d.png)

**Comment by mlachkar** [comment]
C'est bizarre d'afficher les "actual talks" en public. on pourrait dire que public, veut juste dire que cest public pour les orga des meetups ( et non sur la page non authentifié). 
Surtout si c'est un talk tout pourri ^^... je pense que c'est pas interessant d'afficher les talks pending ou refusé , meme si ils sont public .. 
Bon l'autre aspect qui me fait contredire avec moi même, cest dans le cas où les speakers veulent répertorier l'ensemble de leur talks, avec les liens youtube et description, pour avoir un profil complet public .. 

Par contre le "Actual talks", est vraiment pas clair.. les planned talks c'est pas des actuals talks ?

**Comment by loicknuchel** [comment]
Pour les "actual talks", c'est les talks que le speaker a mis en "Public" (il peut les mettre en "Listed" s'il veut pas qu'ils soient présents là mais que les orgas puissent les voir), ou "Private" s'il veut les garder pour lui. Du coup, s'ils sont Public, à priori c'est qu'il veut qu'ils soient là. L'idée c'est de montrer les talks que le speaker est capable de faire actuellement (qui ne sont pas forcément faits d'ailleurs).
Pour les "planned talks", c'est ses proposals (pas des talks techniquement parlant) qui ont été acceptés par des groupes. C'est des "talks" (proposals en fait ^^) qui sont déjà publics sur les événements des groupes et sont juste repris sur la page du speaker, c'est un peu son historique de speaker. On pourrait ajouter une option pour que le speaker puisse les masquer s'il ne souhaite pas qu'ils apparaissent sur sa page, à voir...

Est-ce que c'est plus clair? T'as des idées de comment le rendre plus clair?

**Comment by mlachkar** [comment]
Je comprends parfaitement la distinction entre talks et proposals (l'un n'étant que l'occurence de l'autre). 
Je pense à un UI plus marrante où au haut on a l'ensemble des talks qu'il a choisis de mettre en publiques, et puis les groupes dont il est admin, puis en dernière section , une timeline qui répertorie les proposal accepté dans un orde chronologique. 

Ce qui est interessant, qu'on peut faire pareil pour le profil privée, qui lui affichera l'ensemble de ses talks (avec le bouton "rendre publique" ..) et l'ensemble de la timeline, avec les évenement : talks proposé à ce cftp, talk refusé, commentaire ajouté sur proposal ...

**Comment by loicknuchel** [comment]
Effectivement le côté timeline me semble très intéressant (éventuellement avec pas mal d'événements différents).
Samir est en train de bosser sur les mockups publics, ça va beaucoup évoluer. Côté privé, on pourrait reprendre ça aussi... Il faudrait en discuter un peu plus précisément

**Comment by mlachkar** [comment]
Je ne sais pas ce que veux dire mockups public, mais si tu dis que c'est bien :) 
Je viens de lire tes issues ouvertes, et je pense que mon idée ressemble a ta proposition d'history d'évènements. Et pareil j'imagine un truc qui ressemble au profil de github que je trouve interessant et plutôt complet.
